# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pcorlys- <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/12/05 08:12:05 by pcorlys-          #+#    #+#              #
#    Updated: 2018/12/05 08:19:46 by pcorlys-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror -c  main.c
	gcc  main.o -o ft_display_file
clean:
	rm -rf main.o

fclean: clean
	rm -rf ft_display_file
